name: playstation_game
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.4
  retrofit: ^3.0.1
  json_serializable: ^5.0.2
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  flutter_html: ^2.2.1
  html: ^0.15.0
  flutter_spinkit: ^5.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^3.0.1+1
  build_runner: any


flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf

  assets:
    - images/
